### Get Access Token
POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YzdiOTMwZjZmZWM0NDA2ZmIwYTIxM2QyOWIyMTdiNGU6MjA4N2NhYWEwMmQwNDZjMDhhYzdjYjZhZmYzMDk5ZWQ=

grant_type=client_credentials&client_id=c7b930f6fec4406fb0a213d29b217b4e&client_secret=2087caaa02d046c08ac7cb6aff3099ed

### Search for a Track
GET https://api.spotify.com/v1/search?q=track:Blinding%20Lights%20artist:The%20Weeknd&type=track&limit=1
Authorization: Bearer BQAL9aQAnOq1Z-hE4VAhNfXokr3oRdo3PHrXZTHvBYxGX5K0sQn_CLq7pLAoQ8yH5G6iIkZIRJOLEy7agWkiV24pcTbEKduaUGJRN32Q0wq9BJLLphymU0zSY2oHYhIOmKJHCXAiKJI

### echo -n "c7b930f6fec4406fb0a213d29b217b4e:2087caaa02d046c08ac7cb6aff3099ed" | base64